In [4]:
import keras
from keras.models import Sequential
from keras.layers import Dense
import pandas as pd

In [6]:
concrete_data = pd.read_csv('https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv')
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [7]:
columns = concrete_data.columns

predictors = concrete_data[columns[columns != 'Strength']]
target = concrete_data['Strength']

In [8]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [9]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

In [10]:
# normalize the data
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [11]:
n_cols = predictors_norm.shape[1]

In [12]:
def regression_model():
  model = Sequential()
  model.add(Dense(5, activation='relu', input_shape=(n_cols,)))
  model.add(Dense(5, activation='relu'))
  model.add(Dense(1))

  model.compile(optimizer='adam', loss='mean_squared_error')
  return model

In [13]:
model = regression_model()

model.fit(predictors_norm, target, validation_split=0.3, epochs=100, verbose=2)

Epoch 1/100

/home/kayaman/Projects/venv/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

23/23 - 1s - 26ms/step - loss: 1652.0627 - val_loss: 1185.5906
Epoch 2/100
23/23 - 0s - 2ms/step - loss: 1633.0070 - val_loss: 1170.9484
Epoch 3/100
23/23 - 0s - 2ms/step - loss: 1613.6829 - val_loss: 1156.2681
Epoch 4/100
23/23 - 0s - 2ms/step - loss: 1593.6737 - val_loss: 1140.5565
Epoch 5/100
23/23 - 0s - 1ms/step - loss: 1571.9529 - val_loss: 1124.5854
Epoch 6/100
23/23 - 0s - 1ms/step - loss: 1548.2992 - val_loss: 1107.4237
Epoch 7/100
23/23 - 0s - 2ms/step - loss: 1521.9060 - val_loss: 1088.3346
Epoch 8/100
23/23 - 0s - 1ms/step - loss: 1491.7661 - val_loss: 1067.6052
Epoch 9/100
23/23 - 0s - 1ms/step - loss: 1458.9142 - val_loss: 1043.8918
Epoch 10/100
23/23 - 0s - 1ms/step - loss: 1421.0197 - val_loss: 1018.5445
Epoch 11/100
23/23 - 0s - 1ms/step - loss: 1379.7401 - val_loss: 990.8541
Epoch 12/100
23/23 - 0s - 1ms/step - loss: 1333.6223 - val_loss: 961.1537
Epoch 13/100
23/23 - 0s - 1ms/step - loss: 1283.3136 - val_loss: 929.0977
Epoch 14/100
23/23 - 0s - 1ms/step - loss: 1228.6075 - val_loss: 895.0211
Epoch 15/100
23/23 - 0s - 2ms/step - loss: 1169.4475 - val_loss: 858.5594
Epoch 16/100
23/23 - 0s - 1ms/step - loss: 1106.3281 - val_loss: 820.3436
Epoch 17/100
23/23 - 0s - 2ms/step - loss: 1039.8794 - val_loss: 781.3940
Epoch 18/100
23/23 - 0s - 2ms/step - loss: 970.4129 - val_loss: 740.5065
Epoch 19/100
23/23 - 0s - 1ms/step - loss: 898.8604 - val_loss: 699.6277
Epoch 20/100
23/23 - 0s - 1ms/step - loss: 826.9473 - val_loss: 658.1621
Epoch 21/100
23/23 - 0s - 1ms/step - loss: 754.8494 - val_loss: 617.3523
Epoch 22/100
23/23 - 0s - 1ms/step - loss: 684.6627 - val_loss: 577.3976
Epoch 23/100
23/23 - 0s - 1ms/step - loss: 617.9280 - val_loss: 538.6256
Epoch 24/100
23/23 - 0s - 1ms/step - loss: 555.1145 - val_loss: 501.0539
Epoch 25/100
23/23 - 0s - 1ms/step - loss: 497.8896 - val_loss: 466.2206
Epoch 26/100
23/23 - 0s - 1ms/step - loss: 445.6356 - val_loss: 434.5073
Epoch 27/100
23/23 - 0s - 1ms/step - loss: 400.5122 - val_loss: 405.9871
Epoch 28/100
23/23 - 0s - 1ms/step - loss: 361.7776 - val_loss: 379.8056
Epoch 29/100
23/23 - 0s - 1ms/step - loss: 327.6456 - val_loss: 357.3084
Epoch 30/100
23/23 - 0s - 1ms/step - loss: 300.2645 - val_loss: 337.9493
Epoch 31/100
23/23 - 0s - 1ms/step - loss: 277.5375 - val_loss: 320.9509
Epoch 32/100
23/23 - 0s - 1ms/step - loss: 259.2342 - val_loss: 306.6678
Epoch 33/100
23/23 - 0s - 1ms/step - loss: 244.6512 - val_loss: 293.9436
Epoch 34/100
23/23 - 0s - 1ms/step - loss: 233.0708 - val_loss: 282.5816
Epoch 35/100
23/23 - 0s - 1ms/step - loss: 223.8591 - val_loss: 273.0410
Epoch 36/100
23/23 - 0s - 2ms/step - loss: 216.4290 - val_loss: 265.2955
Epoch 37/100
23/23 - 0s - 1ms/step - loss: 210.4821 - val_loss: 259.5497
Epoch 38/100
23/23 - 0s - 1ms/step - loss: 205.7263 - val_loss: 252.9555
Epoch 39/100
23/23 - 0s - 2ms/step - loss: 201.4075 - val_loss: 246.9585
Epoch 40/100
23/23 - 0s - 1ms/step - loss: 197.9085 - val_loss: 241.7216
Epoch 41/100
23/23 - 0s - 1ms/step - loss: 194.8374 - val_loss: 237.0838
Epoch 42/100
23/23 - 0s - 1ms/step - loss: 192.1629 - val_loss: 233.3672
Epoch 43/100
23/23 - 0s - 1ms/step - loss: 189.8688 - val_loss: 228.9757
Epoch 44/100
23/23 - 0s - 2ms/step - loss: 187.6605 - val_loss: 226.3639
Epoch 45/100
23/23 - 0s - 1ms/step - loss: 185.6151 - val_loss: 221.4877
Epoch 46/100
23/23 - 0s - 1ms/step - loss: 183.8398 - val_loss: 218.5591
Epoch 47/100
23/23 - 0s - 2ms/step - loss: 182.1297 - val_loss: 215.4739
Epoch 48/100
23/23 - 0s - 1ms/step - loss: 180.6355 - val_loss: 212.2085
Epoch 49/100
23/23 - 0s - 1ms/step - loss: 179.2923 - val_loss: 208.8338
Epoch 50/100
23/23 - 0s - 1ms/step - loss: 177.9475 - val_loss: 206.5557
Epoch 51/100
23/23 - 0s - 2ms/step - loss: 176.7048 - val_loss: 202.8763
Epoch 52/100
23/23 - 0s - 1ms/step - loss: 175.5939 - val_loss: 200.6361
Epoch 53/100
23/23 - 0s - 1ms/step - loss: 174.3967 - val_loss: 197.6865
Epoch 54/100
23/23 - 0s - 1ms/step - loss: 173.4154 - val_loss: 193.9814
Epoch 55/100
23/23 - 0s - 1ms/step - loss: 172.3244 - val_loss: 192.1510
Epoch 56/100
23/23 - 0s - 1ms/step - loss: 171.4207 - val_loss: 190.8250
Epoch 57/100
23/23 - 0s - 1ms/step - loss: 170.4554 - val_loss: 188.4894
Epoch 58/100
23/23 - 0s - 1ms/step - loss: 169.5453 - val_loss: 186.1729
Epoch 59/100
23/23 - 0s - 1ms/step - loss: 168.6344 - val_loss: 184.0251
Epoch 60/100
23/23 - 0s - 1ms/step - loss: 167.9268 - val_loss: 180.9254
Epoch 61/100
23/23 - 0s - 1ms/step - loss: 166.9347 - val_loss: 178.6616
Epoch 62/100
23/23 - 0s - 1ms/step - loss: 166.1904 - val_loss: 177.3958
Epoch 63/100
23/23 - 0s - 1ms/step - loss: 165.4121 - val_loss: 175.9283
Epoch 64/100
23/23 - 0s - 1ms/step - loss: 164.6160 - val_loss: 173.5222
Epoch 65/100
23/23 - 0s - 1ms/step - loss: 163.9249 - val_loss: 171.5261
Epoch 66/100
23/23 - 0s - 1ms/step - loss: 163.2204 - val_loss: 169.4729
Epoch 67/100
23/23 - 0s - 1ms/step - loss: 162.6758 - val_loss: 168.0228
Epoch 68/100
23/23 - 0s - 1ms/step - loss: 161.9496 - val_loss: 166.6526
Epoch 69/100
23/23 - 0s - 1ms/step - loss: 161.1898 - val_loss: 164.6127
Epoch 70/100
23/23 - 0s - 2ms/step - loss: 160.6010 - val_loss: 163.1619
Epoch 71/100
23/23 - 0s - 1ms/step - loss: 160.0635 - val_loss: 161.7952
Epoch 72/100
23/23 - 0s - 2ms/step - loss: 159.5377 - val_loss: 160.1525
Epoch 73/100
23/23 - 0s - 2ms/step - loss: 158.8843 - val_loss: 159.3790
Epoch 74/100
23/23 - 0s - 1ms/step - loss: 158.3661 - val_loss: 157.6942
Epoch 75/100
23/23 - 0s - 2ms/step - loss: 157.8858 - val_loss: 156.3359
Epoch 76/100
23/23 - 0s - 1ms/step - loss: 157.2610 - val_loss: 155.2303
Epoch 77/100
23/23 - 0s - 1ms/step - loss: 156.6059 - val_loss: 153.7357
Epoch 78/100
23/23 - 0s - 1ms/step - loss: 156.0796 - val_loss: 152.2503
Epoch 79/100
23/23 - 0s - 1ms/step - loss: 155.5444 - val_loss: 150.5732
Epoch 80/100
23/23 - 0s - 2ms/step - loss: 155.0228 - val_loss: 149.6805
Epoch 81/100
23/23 - 0s - 2ms/step - loss: 154.4317 - val_loss: 148.8689
Epoch 82/100
23/23 - 0s - 2ms/step - loss: 153.8092 - val_loss: 147.0164
Epoch 83/100
23/23 - 0s - 2ms/step - loss: 153.2023 - val_loss: 146.4246
Epoch 84/100
23/23 - 0s - 2ms/step - loss: 152.7120 - val_loss: 145.0803
Epoch 85/100
23/23 - 0s - 1ms/step - loss: 152.1557 - val_loss: 143.7195
Epoch 86/100
23/23 - 0s - 2ms/step - loss: 151.7125 - val_loss: 143.2800
Epoch 87/100
23/23 - 0s - 2ms/step - loss: 151.1054 - val_loss: 142.2482
Epoch 88/100
23/23 - 0s - 1ms/step - loss: 150.5607 - val_loss: 141.1382
Epoch 89/100
23/23 - 0s - 1ms/step - loss: 150.2216 - val_loss: 140.2023
Epoch 90/100
23/23 - 0s - 1ms/step - loss: 149.6926 - val_loss: 139.5262
Epoch 91/100
23/23 - 0s - 1ms/step - loss: 149.2030 - val_loss: 138.0525
Epoch 92/100
23/23 - 0s - 1ms/step - loss: 148.7716 - val_loss: 137.9004
Epoch 93/100
23/23 - 0s - 1ms/step - loss: 148.3554 - val_loss: 137.0392
Epoch 94/100
23/23 - 0s - 1ms/step - loss: 147.9164 - val_loss: 136.5593
Epoch 95/100
23/23 - 0s - 2ms/step - loss: 147.4789 - val_loss: 135.5031
Epoch 96/100
23/23 - 0s - 2ms/step - loss: 147.1219 - val_loss: 135.0778
Epoch 97/100
23/23 - 0s - 2ms/step - loss: 146.7334 - val_loss: 134.1599
Epoch 98/100
23/23 - 0s - 2ms/step - loss: 146.2778 - val_loss: 133.5993
Epoch 99/100
23/23 - 0s - 2ms/step - loss: 145.8613 - val_loss: 133.1951
Epoch 100/100
23/23 - 0s - 1ms/step - loss: 145.5936 - val_loss: 132.3691